### ISSUE TITLE
It would be convenient in the method WiremockConfigFactory.create() transmit ExtensionContext

### ISSUE THREAD

**Issue by vrudyuk** [lanwen/wiremock-junit5#9]
There was a need from CustomWireMockConfigFactory to access to spring context. I can realize my own ApplicationContextAware and to get context from static method. But would be convenient to get it from ExtensionContext in CustomWireMockConfigFactory instance.

**Comment by davinkevin** [comment]
Would be very helpfull in order to be able to configure depending of the spring context too.
